# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: OpenPDFSaucer maven build
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Java
    strategy:
      matrix:
        java-version: [21, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Check Maven Version
        run: mvn -v; echo "** ls **"; pwd && ls -l

      - name: Build with Maven
        run: mvn -B install --file pom.xml
